# Generated by Django 3.0.8 on 2020-09-15 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(help_text='title for the forum', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Please enter atleast 2 character')]),
        ),
    ]
